name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you build (e.g., npm run build), do it here, then rsync the output

      - name: Install ssh client
        run: sudo apt-get update && sudo apt-get install -y openssh-client rsync

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H your.server.ip >> ~/.ssh/known_hosts

      - name: Sync site
        run: |
          rsync -az --delete ./  ubuntu@your.server.ip:/srv/www/gpsupply/
      
      - name: Reload Apache
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@your.server.ip "sudo systemctl reload apache2"
